---
- name: Ensure 'man' directory exists.
  file:
    path: /usr/share/man/man1
    state: directory
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Ensure Java is installed.
  apt:
    name: "{{ java_packages }}"
    state: present

- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home