Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.define "logstash-vvm" do |machine|
    machine.ssh.insert_key = false
    machine.vm.network "private_network", ip: "192.168.255.102"
    # machine.vm.network :bridge => 'eth0'
    machine.ssh.private_key_path = [".ssh/vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
    machine.vm.provision "file", source: ".ssh/vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"

    machine.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    # machine.vm.network "forwarded_port", guest: 22, host: 22
    # machine.vm.network "forwarded_port", guest: 5000, host: 5000
    # machine.vm.network "forwarded_port", guest: 2812, host: 2812
    # machine.vm.network "forwarded_port", guest: 9100, host: 9100
  end
end