---
- name: HTTPS APT transport for Elasticsearch repository.
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
    state: present
    update_cache: true

- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: "{{ elasticsearch_package_state }}"

- name: Configure Elasticsearch.
  template:
    src: "{{ item }}.j2"
    dest: /etc/elasticsearch/{{ item }}
    owner: root
    group: elasticsearch
    mode: 0660
  with_items:
    - elasticsearch.yml
    - jvm.options

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300

- name: Create elasticsearch plugins directory
  file:
    path: /home/vagrant/es_plugins
    state: directory

- name: Install elasticsearch plugin - elasticsearch-HQ 
  shell:
    cmd: |
      git clone https://github.com/ElasticHQ/elasticsearch-HQ
      cd elasticsearch-HQ
      python3 -m pip install -r requirements.txt
    chdir: /home/vagrant/es_plugins/

- name: Enable elasticsearch plugin - elasticsearch-HQ
  shell: nohup python3 /home/vagrant/es_plugins/elasticsearch-HQ/application.py </dev/null >/dev/null 2>&1 &
  # async: 45
  # poll: 0

- name: Install elasticsearch plugin - elasticsearch-head 
  shell:
    cmd: |
      git clone git://github.com/mobz/elasticsearch-head.git
      cd elasticsearch-head
      npm install
    chdir: /home/vagrant/es_plugins/

- name: Enable elasticsearch plugin - elasticsearch-head
  shell: 
    cmd: |
      cd /home/vagrant/es_plugins/elasticsearch-head 
      nohup npm run start </dev/null >/dev/null 2>&1 &
  # async: 45
  # poll: 0

# - name: Install elasticsearch plugin - elasticsearch-head