---
- name: Perform logstash playbook
  hosts: all
  become: yes
  

  roles:
    - { role: apt, apt_packages: [ git, htop, net-tools, python3-pip, nodejs, npm ], when: ansible_system == 'Linux' }
    - ntp
    - monit
    - java
    - elasticsearch
    - logstash

  # PS
  tasks:
    - name: Get virtual machine id
      shell: ps -e | grep "VBox" | awk 'NR==1{print $1}'
      register: unique_id

    - name: Create final ini file
      ini_file: 
        dest: /etc/ab-logstash-ini
        section: general 
        option: uniqueID 
        value: "{{unique_id.stdout}}" 
        mode: 0600